@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.toblexson.stoned.dataproviders;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;